name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - uses: actions/cache@v4
        name: Cache node_modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: bun install

      - name: Run build
        run: bun build main.ts >> /dev/null

      - name: Run biome lint
        run: bunx biome lint

      - name: Run biome format
        run: bunx biome format
